runtime: python27
env: flex
api_version: 1
entrypoint: {entrypoint}
threadsafe: true

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)